# Generated by Django 3.1.4 on 2021-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenknight', '0002_auto_20210118_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_only',
            field=models.BooleanField(default=False),
        ),
    ]
