# Generated by Django 3.1.4 on 2021-01-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenknight', '0003_product_digital_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
